export const LANGUAGE = {
  KO: {
    TWO_DIGITS: "ko",
    LIBRARY: "라이브러리",
    CATEGORY: {
      VODStudio: "JW 방송",
      VODChildren: "어린이",
      VODTeenagers: "청소년",
      VODFamily: "가족",
      VODProgramsEvents: "프로그램과 행사",
      VODOurActivities: "우리의 활동",
      VODMinistry: "집회와 전도 활동",
      VODOurOrganization: "우리의 조직",
      VODBible: "성경",
      VODMovies: "드라마",
      VODSeries: "연재 동영상",
      VODMusicVideos: "음악",
      VODIntExp: "인터뷰와 경험담",
      VODAudioDescriptions: "화면 해설",
    },
    SUB_CATEGORY: {
      VODStudio: {
        StudioFeatured: "주요 프로그램",
        StudioMonthlyPrograms: "월간 프로그램",
        StudioTalks: "연설",
        StudioNewsReports: "뉴스 및 광고",
      },
      VODChildren: {
        BJF: "동영상 학습 자료",
        ChildrenSongs: "노래",
        ChildrenMovies: "드라마",
      },
      VODTeenagers: {
        TeenSpiritualGrowth: "영적 성장",
        TeenSocialLife: "대인 관계",
        TeenGoals: "목표",
        TeenWhatPeersSay: "인터뷰와 경험담",
        TeenMovies: "드라마",
      },
      VODFamily: {
        FamilyChallenges: "가족이 어려움을 겪을 때",
        FamilyDatingMarriage: "데이트와 결혼",
        FamilyWorship: "가족 숭배",
        FamilyMovies: "드라마",
      },
      VODProgramsEvents: {
        VODPgmEvtMorningWorship: "아침 숭배",
        VODPgmEvtSpecial: "특별 행사",
        VODPgmEvtGilead: "길르앗 학교 졸업식",
        VODPgmEvtAnnMtg: "연례 총회",
        "2025Convention": "2025 순결한 숭배 대회",
        "2024Convention": "2024 '좋은 소식을 전하십시오!' 대회",
        "2023Convention": "2023 '참을성을 나타내십시오!' 대회",
        "2022Convention": "2022 ‘평화를 추구하십시오!’ 대회",
        "2021Convention": "2021 믿음으로 강력해지십시오! 대회",
        "2020Convention": "2020 ‘항상 기뻐하십시오!’ 대회",
        "2019Convention": "2019 ‘사랑은 없어지지 않습니다!’ 대회",
        "2018Convention": "2018 “용기를 내십시오!” 대회",
        "2017Convention": "2017 포기하지 마십시오! 대회",
        "2016Convention": "2016 여호와께 충성을 다하십시오! 대회",
        "2015Convention": "2015 예수를 본받으십시오! 대회",
        "2014Convention": "2014 하느님의 왕국을 계속 첫째로 구하십시오! 대회",
      },
      VODOurActivities: {
        VODActivitiesTranslation: "번역",
        VODActivitiesAVProduction: "오디오 및 동영상 제작",
        VODActivitiesPrintingShipping: "인쇄 및 발송",
        VODActivitiesConstruction: "건축",
        VODActivitiesReliefWork: "구호 활동",
        VODActivitiesTheoSchools: "신권 학교들과 훈련",
        VODActivitiesSpecialEvents: "특별 행사",
      },
      VODMinistry: {
        VODMinistryMidweekMeeting: "평일 집회",
        VODMinistryTools: "전도할 때 사용해 보세요",
        VODMinistryTeachings: "성경의 기본 가르침",
        VODMinistryImproveSkills: "더 능숙해지기",
        VODMinistryMethods: "전도하는 방법",
        VODMinistryExpandMinistry: "우리의 봉사를 확장하는 방법",
        MeetingsConventions: "집회와 크고 작은 대회",
        VODSampleConversations: "대화 방법 제안 (2016-2023)",
      },
      VODOurOrganization: {
        Reports: "세계 전역에서 들어온 보고",
        VODOrgBethel: "베델",
        AccomplishMinistry: "봉사의 직무를 수행하기 위해 조직됨",
        VODOrgHistory: "역사",
        VODOrgLegal: "법적 상황",
        VODOrgBloodlessMedicine: "무수혈 치료",
      },
      VODBible: {
        BibleBooks: "성경의 책들",
        VODBibleTeachings: "성경의 가르침",
        VODBibleAccounts: "성경 이야기",
        VODBibleMedia: "인물, 장소, 사물",
        VODBibleTranslations: "성경 번역",
        VODBiblePrinciples: "성경 원칙 적용하기",
        VODBibleCreation: "창조",
      },
      VODMovies: {
        DramasGoodNews: "예수께서 전하신 좋은 소식",
        VODMoviesBibleTimes: "성경 시대",
        VODMoviesModernDay: "현대",
        VODMoviesExtras: "특별 영상",
        VODMoviesAnimated: "애니메이션",
      },
      VODSeries: {
        VODMinistryApplyTeaching: "읽고 가르치는 기술을 발전시키십시오",
        SeriesBJFSongs: "여호와의 친구가 되세요-노래",
        SeriesBJFLessons: "여호와의 친구가 되세요—동영상",
        SeriesBibleTeachings: "성경의 기본 가르침",
        SeriesHappyMarriage: "결혼 생활이 행복하려면",
        SeriesImitateFaith: "훌륭한 믿음의 본",
        SeriesBibleBooks: "성경 책 소개",
        SeriesIronSharpens: "철이 철을 날카롭게 한다",
        SeriesJehovahsFriends: "여호와의 친구들에게 배우세요",
        SeriesLearnFromThem: "이 사람들을 본받으십시오",
        SeriesWTLessons: "파수대에서 배운 교훈",
        VODLovePeople: "사람들을 사랑하고 제자로 삼으십시오",
        SeriesMyTeenLife: "나의 십 대 이야기",
        SeriesNeetaJade: "니타와 제이드",
        SeriesOrgAccomplishments: "우리의 조직이 이루고 있는 일들",
        SeriesOurHistory: "살아 움직이는 우리의 역사",
        VODPureWorshipIntro: "순결한 숭배—각 장 소개",
        SeriesReasonsFaith: "내 믿음의 이유",
        SeriesBibleChangesLives: "성경이 생활을 변화시키다",
        SeriesGoodNews: "예수께서 전하신 좋은 소식",
        SeriesTruthTransforms: "진리가 인생을 바꾸다",
        SeriesOriginsLife: "생명의 기원에 대한 견해",
        SeriesWasItDesigned: "진화의 산물인가?",
        SeriesWhatPeersSay: "청소년들이 하는 이야기",
        SeriesWhereAreTheyNow: "그들은 지금 어떻게 살고 있습니까?",
        SeriesWhiteboard: "화이트보드 애니메이션",
      },
      VODMusicVideos: {
        VODOriginalSongs: "오리지널송",
        VODSJJMeetings: "'기쁨으로 노래하라'—집회",
        ChildrensSongs: "어린이 노래",
        VODConvMusic: "대회 음악 동영상",
        MakingMusic: "음악 제작",
        VODSingToJah: "여호와께 노래하라",
      },
      VODIntExp: {
        VODIntExpTransformations: "진리가 인생을 바꾸다",
        VODIntExpBlessings: "신성한 봉사에서 누리는 축복",
        VODIntExpEndurance: "시련을 인내하다",
        VODIntExpYouth: "청소년",
        OriginsLife: "과학",
        VODIntExpArchives: "역사의 발자취",
      },
      VODAudioDescriptions: {
        VODMidweekMeetingAD: "평일 집회",
        VODBiblePrinciplesAD: "성경 원칙 적용하기",
        SeriesBJFLessonsAD: "여호와의 친구가 되세요—동영상",
        VODLFFVideosAD: "행복한 삶을 영원히 누리십시오!—동영상",
        VODFamilyAD: "가족",
        SeriesHappyMarriageAD: "결혼 생활이 행복하려면",
        VODIntExpAD: "인터뷰와 경험담",
        VODBibleBooksAD: "성경 책 소개",
        VODStudioAD: "JW 방송",
        SeriesJehovahsFriendsAD: "여호와의 친구들에게 배우세요",
        SeriesLearnFromThemAD: "이 사람들을 본받으십시오",
        VODLovePeopleAD: "사람들을 사랑하고 제자로 삼으십시오",
        SeriesMyTeenLifeAD: "나의 십 대 이야기",
        OrgAccomplishmentsAD: "우리의 조직이 이루고 있는 일들",
        VODOriginalSongsAD: "오리지널송",
        VODOurActivitiesAD: "우리의 활동",
        SeriesOurHistoryAD: "살아 움직이는 우리의 역사",
        VODMinistryAD: "집회와 전도 활동",
        VODOurOrganizationAD: "우리의 조직",
        VODProgramsEventsAD: "프로그램과 행사",
        SeriesReasonsFaithAD: "내 믿음의 이유",
        VODSJJMeetingsAD: "'기쁨으로 노래하라'—집회",
        VODTeenagersAD: "나의 십 대 이야기",
        VODBibleAD: "성경",
        VODMinistryToolsAD: "전도할 때 사용해 보세요",
        VODIntExpTransformationsAD: "진리가 인생을 바꾸다",
        SeriesWhiteboardAD: "화이트보드 애니메이션",
        "2025ConventionAD": "2025 '순결한 숭배' 대회",
        "2024ConventionAD": "2024 '좋은 소식을 전하십시오!' 대회",
        "2023ConventionAD": "2023 '참을성을 나타내십시오!' 대회",
        "2022ConventionAD": "2022 '평화를 추구하십시오!' 대회",
        "2021ConventionAD": "2021 믿음으로 강력해지십시오! 대회",
        "2020ConventionAD": "2020 '항상 기뻐하십시오!' 대회",
        "2019ConventionAD": "2019 ‘사랑은 없어지지 않습니다!’ 대회",
        "2016ConventionAD": "2016 여호와께 충성을 다하십시오! 대회",
      },
    },
  },
  EN: {
    TWO_DIGITS: "en",
    LIBRARY: "library",
    CATEGORY: {},
    SUB_CATEGORY: {},
  },
};
